version: "3.8"
services:
  mongodb: #this is the local db in docker
    image: mongo:5
    restart: always
    ports:
      - 27017:27017

  mongo-seed: #this is used to populate the DB, see dockerfile for import command
    build: ./db-seed
    # image: yourregistry.azurecr.io/bib/mongo-seed
    depends_on:
      - mongodb

  api:
    build:
      context: ./api
    # image: yourregistry.azurecr.io/bib/api
    environment:
      PORT: 4000
      MONGO_URI: mongodb://mongodb:27017/dobook
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
    # image: yourregistry.azurecr.io/bib/frontend
    environment:
      API_HOST: api
      API_PORT: 4000
    links:
      - api
    ports:
      - 80:80
